version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: microservicio2
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_AUTHENTICATION_DATABASE: admin
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - 8081:8081
    depends_on:
      - mongodb

  microservicio1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: microservicio1
    restart: always
    environment:
      MONGODB_URI: 'mongodb://mongodb:27017/microservicio2?authSource=admin'
      MONGODB_USER: admin
      MONGODB_PASSWORD: password
    ports:
      - 3000:3000
    depends_on:
      - mongodb

volumes:
  mongodb_data: